### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by fnattino**
Documentation added to the repository using sphinx. I have imported the repo in [readthedocs](https://lcmacropipeline.readthedocs.io/en/documentation/), let me know if you think anything should be added/modified (you can add comments to the file `docs/user_manual.rst`). 

While writing the docs I have realised the `setup_client` method in the MacroPipeline was not very descriptive (and potentially source of confusion with the webdav-client) - I have thus renamed it `setup_cluster`.

### CODE REVIEW

**Comment by fnattino** [comment]
Great, thanks @rogerkuou . Any issue/limitation you thought we should mention? Otherwise let's leave these sections out for now, one could add them when/if there are elements..

**Comment by meiertgrootes** [comment]
Moving the conversation from teams

======
[11:00] Ou Ku
    I commented to the Documentaion for laserfarm that maybe we need to mention some current limitation for laserfarm? One thing I am bearing in the mind is to state that it has been only tested for AHN case, and may have unknown issue with lat/lon coordinate system, since the tile size is not uniform 
​[11:02] Ou Ku
    But maybe it is also good to only track issues when they happen, and only track it on GitHub to make it centralized
<https://teams.microsoft.com/l/message/19:fd4065edfdcd41c38754375588860c2b@thread.tacv2/1589965221274?tenantId=aa3aeacc-6307-42b2-ac05-787dd5c32574&amp;groupId=3f641c90-a9f9-4c5f-8ba7-8da9bf777826&amp;parentMessageId=1589963572263&amp;teamName=Atlas&amp;channelName=General&amp;createdTime=1589965221274>

=====

**Comment by rogerkuou** [comment]
Hi @fnattino, I am mainly thinking of mentioning the fact that so far we have only tested the laserfarm with AHN3, because there can be unknown issue with other lidar data format, coordinate system or other factors in other countries. These issues remain unknown until someone apply laserfarm+laserchicken in another application.

**Comment by meiertgrootes** [comment]
the vertex structure underlying point clouds in laserchicken should ba bale of handling non-rectilinear coordiante systems, at. least in the sense, that is simply stores values if PDAL can handle the values when provided a coordinate system reference, then the retiling should be fine. After that one is back to rectilinear

**Comment by fnattino** [comment]
PDAL should be able to handle different reference systems (https://pdal.io/tutorial/las.html#spatial-reference-system) including lat/long data (https://pdal.io/workshop/exercises/translation/reprojection.html). Indeed, the data-processing part, which relies on `laserchicken`'s point-cloud arrays should not have issues. And for the GeoTIFF export one would need to specify the correct EPSG code. So it seems all should work fine?

**Comment by meiertgrootes** [comment]
@fnattino I just briefly talked to Ou. You're right, that PDAL could handle other coordinates, but Ou pointed out that we aren't implementing any coordinate transformations is the splitter, i.e we feed pdal a bunch of points, as well as a grinding scheme. This tacitly assumes they're all on the same projection and coordinate system. The splitter then simply retiles the data according to the specifications. This is fine as long as we're using a planar euclidean projection,  as well as possibly lat, long, elevation. In the later case, however, all metrics will fail, as they are based on euclidean plane projections. We should indeed add a preface saying that the code is designed to work with data on a Euclidean plane projection.

**Comment by fnattino** [comment]
Thanks @meiertgrootes and @rogerkuou ! I see, you are absolutely right, I willl add this 'disclaimer'!

**Pull request merged**
